function performERPMeasurements(data_struct, time_window, bin_numbers, channel_numbers, component_name, task_name, results_dir)
% PERFORMERPMEASUREMENTS Performs ERP measurements for specified components
%
% Inputs:
%   data_struct     - Data structure from dir() (filtered or unfiltered)
%   time_window     - Time window vector [start end] for measurements
%   bin_numbers     - Single bin number or array of bin numbers
%   channel_numbers - Single channel or array of channel numbers
%   component_name  - String: 'P3b', 'N2', 'ERN', or 'FRN'
%   task_name       - String: task name for output files (e.g., 'gonogo', 'stroop', 'wcst')
%   results_dir     - Directory path for saving results
%
% Channel mapping: Pz=13, Cz=24, Fz=2
%
% Written by Noor Tasnim on September 26, 2025

    % Validate component name
    valid_components = {'P3b', 'N2', 'ERN', 'FRN'};
    if ~ismember(component_name, valid_components)
        error('Invalid component name. Must be one of: P3b, N2, ERN, FRN');
    end
    
    % Determine if data is filtered or unfiltered based on first dataset
    % name
    if contains(data_struct(1).name, 'filt')
        is_filtered = true;
    else
        is_filtered = false;
    end
    
    % Set component-specific parameters
    if strcmp(component_name, 'P3b')
        peak_polarity = 'positive';
        farea_measure = 'fareaplat';
    else % N2, ERN, FRN
        peak_polarity = 'negative';
        farea_measure = 'fareanlat';
    end
    
    % Channel name mapping
    channel_names = containers.Map([13, 24, 2], {'Pz', 'Cz', 'Fz'});
    
    % Load data

    % Initialize ALLERP structure
    ALLERP = [];
    
    % for idx = 1:length(data_struct)
    %     [ERP ALLERP] = pop_loaderp('filename', data_struct(idx).name,...
    %         'filepath', data_struct(idx).folder);
    % end

    for idx = 1:length(data_struct)
        if idx == 1
            % First file - initialize ALLERP
            [ERP, ALLERP] = pop_loaderp('filename', data_struct(idx).name,...
                'filepath', data_struct(idx).folder);
        else
            % Subsequent files - append to existing ALLERP
            ERP = pop_loaderp('filename', data_struct(idx).name,...
                'filepath', data_struct(idx).folder);
            ALLERP(idx) = ERP;
        end
    end


    
    % Process each channel
    for ch_idx = 1:length(channel_numbers)
        current_channel = channel_numbers(ch_idx);
        
        % Get channel name for file naming
        if isKey(channel_names, current_channel)
            channel_name = channel_names(current_channel);
        else
            channel_name = sprintf('Ch%d', current_channel);
        end

        if ~is_filtered % "~" means NOT filtered
            % UNFILTERED DATA MEASUREMENTS
            
            % 1. Mean Amplitude (same for all components)
            output_file = sprintf('%s%s_%s_%s_MeanAmp.txt', ...
                results_dir, task_name, component_name, channel_name);
            
            ALLERP = pop_geterpvalues(ALLERP, time_window, bin_numbers, current_channel, ...
                'Afraction', 0.5, 'Baseline', 'pre', ...
                'Binlabel', 'on', 'Erpsets', 1:length(data_struct), ...
                'FileFormat', 'long', ...
                'Filename', output_file, ...
                'Fracreplace', 'NaN', 'IncludeLat', 'on', ...
                'InterpFactor', 1, 'Measure', 'meanbl', ...
                'PeakOnset', 1, 'Resolution', 3);
            
            % 2. Fractional Area Latency (50%)
            output_file = sprintf('%s%s_%s_%s_FracAreaLat.txt', ...
                results_dir, task_name, component_name, channel_name);
            
            ALLERP = pop_geterpvalues(ALLERP, time_window, bin_numbers, current_channel, ...
                'Afraction', 0.5, 'Baseline', 'pre', ...
                'Binlabel', 'on', 'Erpsets', 1:length(data_struct), ...
                'FileFormat', 'long', ...
                'Filename', output_file, ...
                'Fracreplace', 'NaN', 'IncludeLat', 'on', ...
                'InterpFactor', 1, 'Measure', farea_measure, ...
                'PeakOnset', 1, 'Resolution', 3);
            
        else
            % FILTERED DATA MEASUREMENTS
            
            % 1. Peak Amplitude
            output_file = sprintf('%s%s_%s_%s_PeakAmp.txt', ...
                results_dir, task_name, component_name, channel_name);
            
            ALLERP = pop_geterpvalues(ALLERP, time_window, bin_numbers, current_channel, ...
                'Afraction', 0.5, 'Baseline', 'pre', ...
                'Binlabel', 'on', 'Erpsets', 1:length(data_struct), ...
                'FileFormat', 'long', ...
                'Filename', output_file, ...
                'Fracreplace', 'NaN', 'IncludeLat', 'on', ...
                'InterpFactor', 1, 'Measure', 'peakampbl', ...
                'Neighborhood', 5, 'PeakOnset', 1, ...
                'Peakpolarity', peak_polarity, ...
                'Peakreplace', 'NaN', 'Resolution', 3);
            
            % 2. Peak Latency
            output_file = sprintf('%s%s_%s_%s_PeakLat.txt', ...
                results_dir, task_name, component_name, channel_name);
            
            ALLERP = pop_geterpvalues(ALLERP, time_window, bin_numbers, current_channel, ...
                'Afraction', 0.5, 'Baseline', 'pre', ...
                'Binlabel', 'on', 'Erpsets', 1:length(data_struct), ...
                'FileFormat', 'long', ...
                'Filename', output_file, ...
                'Fracreplace', 'NaN', 'IncludeLat', 'on', ...
                'InterpFactor', 1, 'Measure', 'peaklatbl', ...
                'Neighborhood', 5, 'PeakOnset', 1, ...
                'Peakpolarity', peak_polarity, ...
                'Peakreplace', 'NaN', 'Resolution', 3);
            
            % 3. Onset Latency
            output_file = sprintf('%s%s_%s_%s_OnsetLat.txt', ...
                results_dir, task_name, component_name, channel_name);
            
            ALLERP = pop_geterpvalues(ALLERP, time_window, bin_numbers, current_channel, ...
                'Afraction', 0.5, 'Baseline', 'pre', ...
                'Binlabel', 'on', 'Erpsets', 1:length(data_struct), ...
                'FileFormat', 'long', ...
                'Filename', output_file, ...
                'Fracreplace', 'NaN', 'IncludeLat', 'on', ...
                'InterpFactor', 1, 'Measure', 'fpeaklat', ...
                'Neighborhood', 3, 'PeakOnset', 1, ...
                'Peakpolarity', peak_polarity, ...
                'Peakreplace', 'NaN', 'Resolution', 3);
        end
    end
    % Completion Message
    fprintf('Measurements completed for %s component in %s task\n', component_name, task_name);
end